local _, ns = ...

local L = ns.L

ns.Constants = {
  defaultProfileName = "Default",
  settingsCategoryName = L.SETTINGS_CATEGORY,
  statDefinitions = {
    { key = "ITEM_MOD_STRENGTH_SHORT", label = ITEM_MOD_STRENGTH_SHORT or "Strength" },
    { key = "ITEM_MOD_AGILITY_SHORT", label = ITEM_MOD_AGILITY_SHORT or "Agility" },
    { key = "ITEM_MOD_INTELLECT_SHORT", label = ITEM_MOD_INTELLECT_SHORT or "Intellect" },
    { key = "ITEM_MOD_STAMINA_SHORT", label = ITEM_MOD_STAMINA_SHORT or "Stamina" },
    { key = "ITEM_MOD_CRIT_RATING_SHORT", label = ITEM_MOD_CRIT_RATING_SHORT or "Critical Strike" },
    { key = "ITEM_MOD_HASTE_RATING_SHORT", label = ITEM_MOD_HASTE_RATING_SHORT or "Haste" },
    { key = "ITEM_MOD_MASTERY_RATING_SHORT", label = ITEM_MOD_MASTERY_RATING_SHORT or "Mastery" },
    { key = "ITEM_MOD_VERSATILITY", label = ITEM_MOD_VERSATILITY or "Versatility" },
  },
  slotCandidates = {
    INVTYPE_HEAD = { INVSLOT_HEAD },
    INVTYPE_NECK = { INVSLOT_NECK },
    INVTYPE_SHOULDER = { INVSLOT_SHOULDER },
    INVTYPE_CHEST = { INVSLOT_CHEST },
    INVTYPE_ROBE = { INVSLOT_CHEST },
    INVTYPE_WAIST = { INVSLOT_WAIST },
    INVTYPE_LEGS = { INVSLOT_LEGS },
    INVTYPE_FEET = { INVSLOT_FEET },
    INVTYPE_WRIST = { INVSLOT_WRIST },
    INVTYPE_HAND = { INVSLOT_HAND },
    INVTYPE_FINGER = { INVSLOT_FINGER1, INVSLOT_FINGER2 },
    INVTYPE_TRINKET = { INVSLOT_TRINKET1, INVSLOT_TRINKET2 },
    INVTYPE_CLOAK = { INVSLOT_BACK },
    INVTYPE_WEAPON = { INVSLOT_MAINHAND, INVSLOT_OFFHAND },
    INVTYPE_2HWEAPON = { INVSLOT_MAINHAND },
    INVTYPE_WEAPONMAINHAND = { INVSLOT_MAINHAND },
    INVTYPE_WEAPONOFFHAND = { INVSLOT_OFFHAND },
    INVTYPE_HOLDABLE = { INVSLOT_OFFHAND },
    INVTYPE_SHIELD = { INVSLOT_OFFHAND },
    INVTYPE_RANGED = { INVSLOT_MAINHAND },
    INVTYPE_RANGEDRIGHT = { INVSLOT_MAINHAND },
    INVTYPE_THROWN = { INVSLOT_MAINHAND },
    INVTYPE_RELIC = { INVSLOT_MAINHAND },
  },
  slotLabels = {
    [INVSLOT_HEAD] = INVTYPE_HEAD or "head",
    [INVSLOT_NECK] = INVTYPE_NECK or "neck",
    [INVSLOT_SHOULDER] = INVTYPE_SHOULDER or "shoulder",
    [INVSLOT_CHEST] = INVTYPE_CHEST or "chest",
    [INVSLOT_WAIST] = INVTYPE_WAIST or "waist",
    [INVSLOT_LEGS] = INVTYPE_LEGS or "legs",
    [INVSLOT_FEET] = INVTYPE_FEET or "feet",
    [INVSLOT_WRIST] = INVTYPE_WRIST or "wrist",
    [INVSLOT_HAND] = INVTYPE_HAND or "hands",
    [INVSLOT_FINGER1] = (INVTYPE_FINGER or "finger") .. " 1",
    [INVSLOT_FINGER2] = (INVTYPE_FINGER or "finger") .. " 2",
    [INVSLOT_TRINKET1] = (INVTYPE_TRINKET or "trinket") .. " 1",
    [INVSLOT_TRINKET2] = (INVTYPE_TRINKET or "trinket") .. " 2",
    [INVSLOT_BACK] = INVTYPE_CLOAK or "back",
    [INVSLOT_MAINHAND] = INVTYPE_WEAPONMAINHAND or "main hand",
    [INVSLOT_OFFHAND] = INVTYPE_WEAPONOFFHAND or "off hand",
  },
  tooltipMethods = {
    "SetBagItem",
    "SetHyperlink",
    "SetInventoryItem",
    "SetItemByID",
    "SetLootItem",
    "SetLootRollItem",
    "SetMerchantItem",
    "SetQuestItem",
    "SetQuestLogItem",
    "SetInboxItem",
    "SetBuybackItem",
    "SetTradePlayerItem",
    "SetTradeTargetItem",
    "SetItemInteractionItem",
  },
}
