local _, BGA = ...

BGA.Core = BGA.Core or {}

local codes = {
    ITEM_DATA_PENDING = "ITEM_DATA_PENDING",
    ITEM_DATA_FAILED = "ITEM_DATA_FAILED",
    ITEM_DATA_TIMEOUT = "ITEM_DATA_TIMEOUT",
    STALE_REQUEST = "STALE_REQUEST",
    INVALID_ITEM_SNAPSHOT = "INVALID_ITEM_SNAPSHOT",
    INVALID_EQUIPMENT_STATE = "INVALID_EQUIPMENT_STATE",
    UNSUPPORTED_INVENTORY_TYPE = "UNSUPPORTED_INVENTORY_TYPE",
    UNSUPPORTED_SPEC = "UNSUPPORTED_SPEC",
    ARCHETYPE_MISMATCH = "ARCHETYPE_MISMATCH",
    MODEL_NOT_VALIDATED = "MODEL_NOT_VALIDATED",
    BASELINE_EFFECT_CONTEXT_MISMATCH = "BASELINE_EFFECT_CONTEXT_MISMATCH",
    OUT_OF_MODEL_DOMAIN = "OUT_OF_MODEL_DOMAIN",
    WRONG_ARMOR_TYPE = "WRONG_ARMOR_TYPE",
    ITEM_NOT_EQUIPPABLE = "ITEM_NOT_EQUIPPABLE",
    UNIQUE_LIMIT_VIOLATION = "UNIQUE_LIMIT_VIOLATION",
    DUPLICATE_INSTANCE = "DUPLICATE_INSTANCE",
    UNKNOWN_STAT_KEY = "UNKNOWN_STAT_KEY",
    SPECIAL_EFFECT_DETECTED = "SPECIAL_EFFECT_DETECTED",
    TRINKET_UNSUPPORTED = "TRINKET_UNSUPPORTED",
    WEAPON_UNSUPPORTED = "WEAPON_UNSUPPORTED",
    TIER_UNSUPPORTED = "TIER_UNSUPPORTED",
    CRAFTED_ITEM_UNSUPPORTED = "CRAFTED_ITEM_UNSUPPORTED",
    CRAFTED_PROJECTION_UNSUPPORTED = "CRAFTED_PROJECTION_UNSUPPORTED",
    LEGACY_OR_INELIGIBLE_TRACK = "LEGACY_OR_INELIGIBLE_TRACK",
    ELIGIBILITY_UNVERIFIED = "ELIGIBILITY_UNVERIFIED",
    UNVERIFIED_SEASON_DATA = "UNVERIFIED_SEASON_DATA",
    AMBIGUOUS_RANK_BONUS = "AMBIGUOUS_RANK_BONUS",
    PROJECTION_ITEM_LEVEL_MISMATCH = "PROJECTION_ITEM_LEVEL_MISMATCH",
    UNCERTAINTY_OVERLAPS_MATERIALITY = "UNCERTAINTY_OVERLAPS_MATERIALITY",
}

BGA.Core.ReasonCodes = codes
